### ISSUE TITLE
2.0.0 Feature Checklist

### ISSUE THREAD

**Issue by Jikoo** [Jikoo/Regionerator#17]
- [x] Store previous visit value for chunks when deleted
- [x] Move delete calls into queue with upserts
- [x] Separate log for errors saving to DB
- [x] DB queue info command
- [x] Fix deletion running concurrently
- [x] Optimize ChunkInfo checks to minimize DB/plugin hook usage
- [x] Add tab completion for commands
- [x] Documentation
